from __future__ import annotations

from dataclasses import dataclass

from financemailparser.domain.beancount_constants import (
    BEANCOUNT_DEFAULT_ASSETS_ACCOUNT,
    BEANCOUNT_DEFAULT_EXPENSES_ACCOUNT,
    BEANCOUNT_DEFAULT_INCOME_ACCOUNT,
    BEANCOUNT_CURRENCY,
)
from financemailparser.infrastructure.beancount.writer import (
    BeancountExportOptions,
    transaction_to_beancount,
    transactions_to_beancount,
)


def test_transaction_to_beancount_expense_direction_and_defaults() -> None:
    out = transaction_to_beancount(
        date="2026-01-01",
        narration="Coffee",
        amount=12.34,
        source="CCB",
    )
    assert out.startswith('2026-01-01 * "Coffee"\n')
    assert (
        f"  {BEANCOUNT_DEFAULT_EXPENSES_ACCOUNT}  12.34 {BEANCOUNT_CURRENCY}\n" in out
    )
    assert f"  {BEANCOUNT_DEFAULT_ASSETS_ACCOUNT}  -12.34 {BEANCOUNT_CURRENCY}\n" in out
    assert "  ; source: CCB\n" in out


def test_transaction_to_beancount_income_direction_and_no_source_comment() -> None:
    options = BeancountExportOptions(include_source_comment=False)
    out = transaction_to_beancount(
        date="2026-01-02",
        narration="Salary",
        amount=-100.0,
        source="X",
        options=options,
    )
    assert "  ; source:" not in out
    assert f"  {BEANCOUNT_DEFAULT_ASSETS_ACCOUNT}  100.00 {BEANCOUNT_CURRENCY}\n" in out
    assert (
        f"  {BEANCOUNT_DEFAULT_INCOME_ACCOUNT}  -100.00 {BEANCOUNT_CURRENCY}\n" in out
    )


def test_transaction_to_beancount_escapes_narration_minimally() -> None:
    out = transaction_to_beancount(
        date="2026-01-03",
        narration='a "b" \\ c ',
        amount=1.0,
        source=None,
    )
    assert out.startswith('2026-01-03 * "a \\"b\\" \\\\ c"\n')


def test_transactions_to_beancount_supports_header_comment_and_object_protocol() -> (
    None
):
    @dataclass(frozen=True)
    class T:
        date: str
        description: str
        amount: float
        source: str

    out = transactions_to_beancount(
        [T(date="2026-01-01", description="X", amount=1.0, source="S")],
        header_comment="generated by tests",
    )
    assert out.startswith("; generated by tests\n\n")
    assert '2026-01-01 * "X"\n' in out
